name: CI
permissions:
  contents: read

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches-ignore:
      - 'gh-readonly-queue/**'
  workflow_dispatch:
  merge_group:
    types: [checks_requested]

env:
  RUSTFLAGS: -Dwarnings
  MACOSX_DEPLOYMENT_TARGET: "14.5"

jobs:
  cache_to_artifact:
    runs-on: ubuntu-latest
    steps:
    - name: Configure Cache Env
      uses: actions/github-script@v6
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
    - uses: actions/checkout@v5
    - run: cargo run
    - name: Upload cache as artifact
      uses: actions/upload-artifact@v4
      with:
        name: cache
        path: cache