name: CI
permissions:
  contents: read

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches-ignore:
      - 'gh-readonly-queue/**'
  workflow_dispatch:
  merge_group:
    types: [checks_requested]

env:
  RUSTFLAGS: -Dwarnings
  MACOSX_DEPLOYMENT_TARGET: "14.5"

jobs:
  cache_to_artifact:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/cache@v4
      with:
        key: '1159e78c4-2025-09-14)-cargo-semver-checks-0.44.0-d41d8cd98f00b204e9800998ecf8427e-semver-checks-rustdoc-4854acc0120975c17defd9b1c649fb889256a863'
        path: cache
    - name: Upload cache as artifact
      uses: actions/upload-artifact@v4
      with:
        name: cache
        path: cache
