name: CI
permissions:
  contents: read

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches-ignore:
      - 'gh-readonly-queue/**'
  workflow_dispatch:
  merge_group:
    types: [checks_requested]

env:
  RUSTFLAGS: -Dwarnings
  MACOSX_DEPLOYMENT_TARGET: "14.5"

jobs:
  cache_to_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Restore cache
        uses: Andrej730/cache/restore@main
        with:
          # Path won't be actually used, we will match by 'version'.
          path: .
          key: 'semver-cargo_semver-93c4e40f0b737772-linux-rustc-1.90.0-(1159e78c4-2025-09-14)-cargo-semver-checks-0.44.0-d41d8cd98f00b204e9800998ecf8427e-semver-checks-rustdoc-4854acc0120975c17defd9b1c649fb889256a863'
          version: '6088e45028fd0140424d7b9ae4d1aafdbac9925f0411980db21f15a236bef626'
      - name: Upload cache as artifact
        uses: actions/upload-artifact@v4
        with:
          name: cache
          path: '.'
